name: deploy cf template

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-2
    - name: run cf template
      run: aws cloudformation deploy --template-file demo-spa.yaml --stack-name resume-spa-cf --parameter-overrides BucketName=${{ secrets.AWS_S3_BUCKET_NAME }} --capabilities CAPABILITY_NAMED_IAM 
    - name: Deploy index S3
      run: aws s3 cp ui/index.html ${{ secrets.AWS_S3_BUCKET }}
    - name: Deploy css
      run: aws s3 cp ui/style.css ${{ secrets.AWS_S3_BUCKET }}
    - name: Deploy favicon
      run: aws s3 cp ui/favicon.ico ${{ secrets.AWS_S3_BUCKET }}
